name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint-format-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: dependencies
        run: npm install

      - name: linter 
        run: npm run lint